import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localfont  from 'next/font/local';
import Navbar from "@/components/ui/navbar";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const podkova = localfont({
    src: [
      {
        path: '../public/fonts/Podkova/static/Podkova-Regular.ttf',
        weight: '400',
      },
      {
        path: '../public/fonts/Podkova/static/Podkova-Bold.ttf'
      }
    ],
    variable: '--font-podkova'
});

const funnel = localfont({
    src: [
      {
        path: '../public/fonts/Funnel_Sans/static/FunnelSans-Regular.ttf',
        weight: '400',
      },
      {
        path: '../public/fonts/Podkova/static/Podkova-Bold.ttf'
      }
    ],
    variable: '--font-funnel'
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${podkova.className} ${funnel.variable} antialiased`}
      >
        <ClerkProvider>
        <Navbar/>
         
          {children}
          <Toaster />
        </ClerkProvider>
      </body>
    </html>
  );
}
